name: scooter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  android_sms_retriever: ^1.3.3
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  custom_logger:
    path: packages/custom_logger
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.2
  geolocator: ^9.0.2
  go_router: ^6.2.0
  hive_storage:
    path: packages/hive_storage
  latlng: ^0.2.0
  location: ^5.0.0-dev.8
  map: ^1.3.5+1
  mobile_scanner: ^3.2.0
  persian_tools:
    path: packages/persian_tools
  provider: ^6.0.3
  qr_code_scanner: ^1.0.1
  safe_change_notifier: ^0.2.0
  sliding_up_panel2: ^3.2.2
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  shimmer: ^3.0.0
  web_service:
    path: packages/web_service
  arna_logger: ^1.1.0
  dotted_border: ^2.1.0
  easy_stepper: ^0.8.1
  another_stepper: ^1.2.2
  group_radio_button: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  # adaptive_icon_background: “assets/images/taalbackground.jpg”
  # adaptive_icon_foreground: “assets/images/appIconForeground.png”
  image_path: "assets/images/appIcon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/YekanBakhEN06Bold.ttf
          weight: 700
        - asset: assets/fonts/YekanBakhEN05Medium.ttf
          weight: 500
        - asset: assets/fonts/YekanBakhEN02Thin.ttf
          weight: 400
